# Generated by Django 4.2.2 on 2023-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="namespaces",
            field=models.JSONField(default=[]),
        ),
    ]
