# Generated by Django 4.2.2 on 2023-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Namespacces",
        ),
    ]
