# Generated by Django 4.2.2 on 2023-06-29 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_rename_article_namespacces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="namespaces",
        ),
    ]
