# Generated by Django 4.2.2 on 2023-07-01 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_remove_user_namespaces"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Namespacces",
            new_name="Namespaces",
        ),
    ]
